build:
  stage: build
  image: ubuntu:22.04
  script:
    - apt-get update && apt-get upgrade -y
    - apt-get install -y build-essential curl
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
    - export PATH=~/.cargo/bin:"${PATH}"
    - cargo build -vv
