image: ubuntu:22.04

before_script:
  - apt-get update
  - apt-get upgrade -y
  - apt-get install -y build-essential curl
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
  - export PATH=~/.cargo/bin:"${PATH}"

build:
  stage: build
  script:
    - export RUSTFLAGS="-D warnings"
    - cargo build -vv

pages:
  stage: deploy
  script:
    - cargo doc
    - mv target/doc public
  artifacts:
    paths:
      - public
  only:
    - master
