[package]
name = "gr-sys"
version = "0.1.0"
edition = "2021"
links = "gr"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = { version = "0.68", default-features = false, features = ["runtime"] }
